apiVersion: apps/v1
kind: Deployment
metadata:
  name: qazaq-learn-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qazaq-learn
  template:
    metadata:
      labels:
        app: qazaq-learn
    spec:
      containers:
        - name: qazaq-learn
          image: qazaq-learn:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qazaq-learn-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: qazaq-learn-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: JWT_EXPIRATION_MS
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SERVER_PORT
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: qazaq-learn-secret
                  key: ENCRYPTION_KEY
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SPRING_DATA_REDIS_PORT
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: qazaq-learn-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
